;;
;; Graph Interface
;; Work in progress
;;

(in-package :cl-synthesizer-graph)

(defgeneric get-inputs-fn (module))
(defgeneric get-inputs (module))
(defgeneric get-outputs-fn (module))
(defgeneric get-outputs (module))
(defgeneric get-update-fn (module))
(defgeneric update (module))
(defgeneric get-state-fn (module))
(defgeneric get-state (module key))
(defgeneric shutdown (module))
(defgeneric get-modules (rack))
(defgeneric get-patches (rack))
(defgeneric is-rack (module))
(defgeneric add-module (rack module-name module-fn &rest args))
(defgeneric get-module-name (rack module))
(defgeneric get-module (rack name))
(defgeneric get-environment (rack))
(defgeneric get-hooks (rack))
(defgeneric add-hook (rack hook))
(defgeneric add-patch (rack output-module-name output-socket input-module-name input-socket))
(defgeneric expose-input-socket (rack rack-input-socket input-module-name input-socket))
(defgeneric expose-output-socket (rack rack-output-socket output-module-name output-socket))
(defgeneric make-patch (&key output-name output-socket input-name input-socket))
(defgeneric get-patch-output-name (patch))
(defgeneric get-patch-output-socket (patch))
(defgeneric get-patch-input-name (patch))
(defgeneric get-patch-input-socket (patch))
(defgeneric get-exposed-input-socket (rack socket))
(defgeneric get-exposed-output-socket (rack socket))
