(in-package :cl-synthesizer-examples)

(defun event-aggregator ()
  (declare (optimize (debug 3) (speed 0) (space 0)))
  ;; events: ( (eventId, count, moduleName, eventName) .... )
  (let ((events nil))
    (list
     :inc
     (lambda (event-id module-name event-name)
       (let ((l (find-if (lambda (i) (eq event-id (first i))) events)))
	 (if (not l)
	     (progn
	       (setf l (list event-id 0 module-name event-name))
	       (push l events)))
	 (let ((c (second l)))
	   (setf (second l) (if c (+ c 1) 1)))))
     :reset (lambda()
	      (dolist (e events)
		(setf (second e) nil)))
     :get-events (lambda () events))))

(defun console-logger (rack)
  (declare (optimize (debug 3) (speed 0) (space 0)))
  (let* ((sample-rate (getf (slot-value rack 'cl-synthesizer::environment) :sample-rate))
	 (every-ticks (/ sample-rate 5))
	 (cur-tick 0)
	 (total-ticks 0)
	 (aggregator (event-aggregator)))
    (labels ((log-event (event-id module-name event-name)
	       (declare (optimize (debug 3) (speed 0) (space 0)))
	       (funcall (getf aggregator :inc) event-id module-name event-name))
	     (flush ()
	       (dolist (event (funcall (getf aggregator :get-events)))
		 (if (second event)
		     (format t "~a: ~a (~a) tickTimestamp: ~a~%"
			     (third event)
			     (fourth event)
			     (second event)
			     total-ticks)))
	       (funcall (getf aggregator :reset))
	       (setf cur-tick 0))
	     (tick ()
	       (declare (optimize (debug 3) (speed 0) (space 0)))
	       (setf total-ticks (+ 1 total-ticks))
	       (setf cur-tick (+ 1 cur-tick))
	       (if (>= cur-tick every-ticks)
		   (flush))))
      (list
       :log #'log-event
       :tick #'tick
       :flush #'flush))))
  

(defun play-rack (rack duration-seconds)
  (let* ((start (get-internal-real-time))
	(ticks-to-play (* duration-seconds (getf (slot-value rack 'cl-synthesizer::environment) :sample-rate)))
	 (console-logger (console-logger rack))
	 (log (getf console-logger :log))
	 (tick (getf console-logger :tick)))
    (format t "~%Ticks to play: ~a~%" ticks-to-play)
    (cl-synthesizer::add-event-listener rack "Console-Logger" log)
    (dotimes (i ticks-to-play)
      (cl-synthesizer::update-rack rack)
      (funcall tick))
    (cl-synthesizer::shutdown-rack rack)
    (funcall (getf console-logger :flush)) 
    (let ((end (get-internal-real-time)))
      (format t "~%Elapsed time in seconds after shutdown: ~a~%" (/ (- end start) internal-time-units-per-second))))
  "DONE")

