(in-package :cl-synthesizer)

(defparameter *home-directory* nil "Optional home-directory setting of cl-synthesizer. Overrides the home-directory argument passed to make-environment.")

(defun get-home-directory (home-directory)
  (cond
    ((not (not *home-directory*))
     *home-directory*)
    ((not (not home-directory))
     home-directory)
    (t
     (user-homedir-pathname))))
  

(defun make-environment (&key (sample-rate 44100) (home-directory nil))
  "Creates an environment. An enviroment is a property list with the following keys:
    <ul>
	<li>:sample-rate Sample rate of the synthesizer.</li>
	<li>:home-directory The root output directory of stuff generated by the synthesizer, such as audio or csv files. Default value is the home directory of the current user. Can be overwritten via cl-synthesizer:*home-directory*.</li>
    </ul>"
  (list
   :sample-rate (coerce sample-rate 'single-float)
   :home-directory (get-home-directory home-directory)))
